// packages/react/src/index.ts
/**
 * React binding for `<openleaf-editor>`.
 *
 * The custom element is the editor. This file is a thin host: it forwards
 * attributes, keeps a controlled `value` in sync, and re-emits `openleaf:change`.
 * Editing logic does not live here, so a React tree cannot fork the schema.
 */

import { createElement, useEffect, useRef, type HTMLAttributes } from 'react'
import '@openleaf-editor/element'

export type OpenLeafEditorProps = HTMLAttributes<HTMLElement> & {
  toolbar?: string
  toolbar2?: string
  menubar?: string | boolean
  formats?: string
  lang?: string
  value?: string
  onOpenLeafChange?: (html: string) => void
}

type Host = HTMLElement & { value: string }

export function OpenLeafEditor({
  value,
  onOpenLeafChange,
  menubar,
  ...rest
}: OpenLeafEditorProps) {
  const ref = useRef<Host>(null)

  useEffect(() => {
    const el = ref.current
    if (!el || value === undefined) return
    if (el.value !== value) el.value = value
  }, [value])

  useEffect(() => {
    const el = ref.current
    if (!el || !onOpenLeafChange) return
    // The element puts the HTML on the event, so reading it here does not cost
    // a second serialization of the document in the same frame. `el.value` is
    // the fallback for an event dispatched by something other than the element.
    const onChange = (event: Event): void => {
      const detail = (event as CustomEvent<{ value?: string } | null>).detail
      onOpenLeafChange(detail?.value ?? el.value)
    }
    el.addEventListener('openleaf:change', onChange)
    return () => {
      el.removeEventListener('openleaf:change', onChange)
    }
  }, [onOpenLeafChange])

  return createElement('openleaf-editor', {
    ...rest,
    ref,
    menubar: menubar === true ? '' : menubar === false ? undefined : menubar,
  })
}

// packages/angular/src/index.ts
/**
 * Angular binding for `<openleaf-editor>`.
 *
 * Standalone component. Import `@openleaf-editor/element` once in the app
 * (this module does that) and use `<openleaf>` in templates. The custom
 * element remains the editor; this class forwards inputs and `valueChange`.
 *
 * `value` and `valueChange` are the pair Angular's two-way syntax expects, so
 * `[(value)]="html"` works, and match what the React and Vue wrappers do.
 */

import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  type AfterViewInit,
  type OnChanges,
  type OnDestroy,
  type SimpleChanges,
} from '@angular/core'
import '@openleaf-editor/element'

type Host = HTMLElement & { value: string }

@Component({
  selector: 'openleaf',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<openleaf-editor
    #editor
    [attr.for]="for"
    [attr.toolbar]="toolbar"
    [attr.toolbar2]="toolbar2"
    [attr.menubar]="menubar"
    [attr.formats]="formats"
    [attr.lang]="lang"
  ></openleaf-editor>`,
})
export class OpenLeafComponent implements AfterViewInit, OnChanges, OnDestroy {
  @ViewChild('editor', { static: true }) editor: ElementRef<Host> | undefined

  @Input() for: string | undefined
  @Input() toolbar: string | undefined
  @Input() toolbar2: string | undefined
  @Input() menubar: string | undefined
  @Input() formats: string | undefined
  @Input() lang: string | undefined
  @Input() value: string | undefined
  @Output() readonly valueChange = new EventEmitter<string>()

  // The element puts the HTML on the event, so reading it here does not cost a
  // second serialization of the document in the same frame. `host.value` is the
  // fallback for an event dispatched by something other than the element.
  private readonly onEditorChange = (event: Event): void => {
    const host = this.editor?.nativeElement
    if (!host) return
    const detail = (event as CustomEvent<{ value?: string } | null>).detail
    this.valueChange.emit(detail?.value ?? host.value)
  }

  ngAfterViewInit(): void {
    const host = this.editor?.nativeElement
    if (!host) return
    this.push(host)
    // Attached here rather than in the template: Angular's parser reads the
    // colon in `openleaf:change` as a namespace separator, so the event cannot
    // be bound declaratively. React and Vue attach it imperatively too.
    host.addEventListener('openleaf:change', this.onEditorChange)
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!('value' in changes)) return
    const host = this.editor?.nativeElement
    if (host) this.push(host)
  }

  ngOnDestroy(): void {
    this.editor?.nativeElement.removeEventListener('openleaf:change', this.onEditorChange)
  }

  /**
   * Write an incoming `value` onto the element, but only when it differs.
   *
   * Assigning unconditionally would replace the document on every change
   * detection pass, which costs the author their selection and their undo
   * history for no change at all.
   */
  private push(host: Host): void {
    if (this.value === undefined) return
    if (host.value !== this.value) host.value = this.value
  }
}
